- hosts: all
  become: yes
  tasks:
   - name: Install Apache
     yum: 
       name: httpd
       state: latest
   - name: Start http
     service:
             name: httpd
             state: started  
             permanent: yes
